language: ruby
dist: bionic

rvm:
  - 2.4
  - 2.5
  - 2.6

bundler_args: --with test
before_install:
  - gem update --system --no-doc
  - gem install bundler --no-doc
  - gem update bundler --no-doc
script:
  - bundle exec rake test
