language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

bundler_args: --with test
before_install:
  - gem update --system --no-doc
  - gem install bundler --no-doc
  - gem update bundler --no-doc
script:
  - bundle exec ruby -Ilib:tests tests/zone_test.rb
