version: 2
jobs:
  ruby26: &base
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rake test
  ruby25:
    <<: *base
    docker:
      - image: circleci/ruby:2.5
  ruby24:
    <<: *base
    docker:
      - image: circleci/ruby:2.5

workflows:
  version: 2
  build:
    jobs:
      - ruby26
      - ruby25
      - ruby24
